CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE TB_BAIRRO   (BAI_CODIGO INTEGER NOT NULL PRIMARY KEY,
                          BAI_DESCRICAO VARCHAR(50) NOT NULL);

CREATE TABLE TB_CIDADE   (CID_CODIGO INTEGER NOT NULL PRIMARY KEY,
                          CID_DESCRICAO VARCHAR(45) NOT NULL);

CREATE TABLE TB_ENDERECO (END_CODIGO INTEGER NOT NULL PRIMARY KEY,
                          END_DESCRICAO VARCHAR(45) NOT NULL);

CREATE TABLE TB_CARGO    (CAR_CODIGO INTEGER NOT NULL PRIMARY KEY,
                          CAR_DESCRICAO VARCHAR(45) NOT NULL,
                          CAR_SALARIOBASE DECIMAL NOT NULL);

CREATE TABLE TB_FUNCIONARIO (FUN_CODIGO INTEGER NOT NULL PRIMARY KEY,
                             FUN_NOME VARCHAR(45) NOT NULL,
                             FUN_RG  VARCHAR(14) NOT NULL,
                             FUN_CPF VARCHAR(14) NOT NULL,
	                       FUN_CODCARGO INTEGER    NOT NULL REFERENCES TB_CARGO(CAR_CODIGO),
                             FUN_CODENDERECO INTEGER NOT NULL REFERENCES TB_ENDERECO(END_CODIGO),
                             FUN_CODBAIRRO   INTEGER NOT NULL REFERENCES TB_BAIRRO(BAI_CODIGO),
                             FUN_CODCIDADE   INTEGER NOT NULL REFERENCES TB_CIDADE(CID_CODIGO));

CREATE TABLE TB_EDITORA (EDI_CODIGO INTEGER NOT NULL PRIMARY KEY,
                         EDI_NOME VARCHAR(45) NOT NULL,
                         EDI_CODENDERECO INTEGER NOT NULL REFERENCES TB_ENDERECO(END_CODIGO),
                         EDI_CODCIDADE   INTEGER NOT NULL REFERENCES TB_CIDADE(CID_CODIGO), 
                         EDI_CODBAIRRO   INTEGER NOT NULL REFERENCES TB_BAIRRO(BAI_CODIGO),
                         EDI_FONE VARCHAR(12) NOT NULL,
                         EDI_CONTATO VARCHAR(10) );


CREATE TABLE TB_CLIENTE (CLI_CODIGO INTEGER NOT NULL PRIMARY KEY, 
                         CLI_NOME VARCHAR(30) NOT NULL,
                         CLI_RG   VARCHAR(14) NOT NULL,
                         CLI_CODENDERECO INTEGER NOT NULL REFERENCES TB_ENDERECO(END_CODIGO),
                         CLI_NUMERO VARCHAR(5),
                         CLI_CODBAIRRO INTEGER NOT NULL REFERENCES TB_BAIRRO(BAI_CODIGO),
                         CLI_CODCIDADE INTEGER NOT NULL REFERENCES TB_CIDADE(CID_CODIGO),
                         CLI_FONE  VARCHAR(12) NOT NULL,
                         CLI_PRAZODEVOL INTEGER NOT NULL, 
                         CLI_CPF  VARCHAR(14));


CREATE TABLE TB_CATEGORIA (CAT_CODIGO INTEGER NOT NULL PRIMARY KEY,
                           CAT_DESCRICAO VARCHAR(20));

CREATE TABLE TB_LIVRO (LIV_CODIGO INTEGER NOT NULL PRIMARY KEY,
                       LIV_TITULO VARCHAR(150) NOT NULL,
                       LIV_CODEDITORA INTEGER NOT NULL REFERENCES TB_EDITORA (EDI_CODIGO),
                       LIV_CODCATEGORIA INTEGER NOT NULL REFERENCES TB_CATEGORIA(CAT_CODIGO),
                       LIV_EDICAO VARCHAR(15) NOT NULL,
                       LIV_ANO    INTEGER NOT NULL,
                       LIV_PRAZOMINIMO VARCHAR(15));


CREATE TABLE TB_AUTOR (AUT_CODIGO INTEGER NOT NULL PRIMARY KEY,
                       AUT_NOME VARCHAR(45) NOT NULL);


CREATE TABLE TB_AUTORLIVRO 
                      (AUTLIV_CODAUTOR INTEGER NOT NULL REFERENCES TB_AUTOR(AUT_CODIGO),
                      AUTLIV_CODLIVRO INTEGER NOT NULL REFERENCES TB_LIVRO(LIV_CODIGO),
	         AUTLIV_PRINCIPAL VARCHAR(3) NOT NULL,
PRIMARY KEY(AUTLIV_CODAUTOR, AUTLIV_CODLIVRO));


CREATE TABLE TB_RESERVA  (RES_CODIGO INTEGER NOT NULL PRIMARY KEY,
                          RES_DATA DATE NOT NULL,
                          RES_CODLIVRO INTEGER NOT NULL REFERENCES TB_LIVRO(LIV_CODIGO),
                          RES_CODFUNC INTEGER NOT NULL REFERENCES TB_FUNCIONARIO(FUN_CODIGO),
                          RES_CODCLIENTE INTEGER NOT NULL REFERENCES TB_CLIENTE(CLI_CODIGO),
                          RES_SITUACAO VARCHAR(10) ); 


CREATE TABLE TB_EXEMPLAR (EXE_CODIGO INTEGER NOT NULL PRIMARY KEY, 
                          EXE_CODLIVRO INTEGER NOT NULL REFERENCES TB_LIVRO(LIV_CODIGO),
                          EXE_STATUS VARCHAR(10) NOT NULL);


CREATE TABLE TB_EMPRESTIMO (EMP_CODIGO INTEGER NOT NULL PRIMARY KEY,
                            EMP_DATA  DATE NOT NULL,
                            EMP_CODCLIENTE INTEGER NOT NULL REFERENCES TB_CLIENTE(CLI_CODIGO),
                            EMP_CODFUNCIONARIO INTEGER NOT NULL REFERENCES TB_FUNCIONARIO(FUN_CODIGO) );


CREATE TABLE TB_EXEMPLAREMPRESTIMO(
	EXEPRE_CODEXEMPLAR	INTEGER	NOT NULL REFERENCES TB_EXEMPLAR(EXE_CODIGO),
	EXEPRE_CODEMPRESTIMO	INTEGER	NOT NULL REFERENCES TB_EMPRESTIMO(EMP_CODIGO),
	EXEPRE_DTPREVDEV DATE NOT NULL,
	EXEPRE_DTDEVMUL DATE,
	EXEPRE_DTPGMUL DATE,
	EXEPRE_CODRESERVA INTEGER REFERENCES TB_RESERVA(RES_CODIGO),
      EXEPRE_VALORMULTA INTEGER NOT NULL,
	PRIMARY KEY(EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO)
	);


