INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (1,'CENTRO');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (2,'CIDADE ALTA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (3,'IPÊ');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (4,'BELO HORIZONTE');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (5,'ITAIPU');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (6,'BNH');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (7,'JARDIM DAS LARANJEIRAS');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (8,'PARQUE INDEPENDÊNCIA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (9,'NAZARÉ');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (10,'SÃO CRISTOVÃO');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (11,'VILA BORGES');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (12,'VILA IOLANDA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (13,'JARDIM SÃO PAULO');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (14,'JARDIM JUPIRA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (15,'TRÊS LAGOAS');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (16,'MORUMBI I');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (17,'VILA PORTES');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (18,'JARDIM PETRÓPOLIS');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (19,'PORTO DA MADEIRA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (20,'CASA AMARELA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (21,'BOA VIAGEM');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (22,'CAMPO GRANDE');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (23,'ENCRUZILHADA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (24,'ARRUDA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (25,'AFLITOS');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (26,'BATEL');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (27,'LEBLON');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (28,'COPACABANA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (29,'RIO DOCE');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (30,'INTERLAGOS');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (31,'TIETÊ');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (32,'JARDIM SÃO PAULO');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (33,'JARDIM ATLÂNTICO');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (34,'UMBURÁ');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (35,'FRIMESA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (36,'PORTO');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (37,'BESSA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (38,'PELORINHO');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (39,'CASA FORTE');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (40,'PARNAMIRIM');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (41,'JOÃO DE BARROS');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (42,'CAIS DO APOLO');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (43,'FLOR DA SERRA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (44,'JARDINÓPOLIS');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (45,'LAPA');
	
INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (46,'BOA VISTA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (47,'JARDIM DAS AÇÕES');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (48,'VILA BRASÍLIA');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (49,'PARQUE PRESIDENTE');

INSERT INTO TB_BAIRRO (BAI_CODIGO,BAI_DESCRICAO)
   VALUES (50,'JARDIM CLÁUDIA');


INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (1,'FOZ DO IGUAÇU');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (2,'ASSIS CHATEUBRIAND');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (3,'CAPITÃO LEONIDAS MARQUES');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (4,'CASCAVEL');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (5,'CATANDUVAS');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (6,'CÉU AZUL');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (7,'CORBÉLIA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (8,'GUARANIAÇU');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (9,'ITAIPULÂNDIA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (10,'MARECHAL CÂNDIDO RONDON');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (11,'MATELÂNDIA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (12,'MEDIANEIRA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (13,'PALOTINA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (14,'PATO BRAGADO');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (15,'QUEDAS DO IGUAÇU');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (16,'RAMILÂNDIA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (17,'SANTA HELENA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (18,'SANTA TEREZINHA DE ITAIPU');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (19,'SÃO MIGUEL DO IGUAÇU');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (20,'SERRANÓPOLIS DO IGUAÇU');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (21,'TOLEDO');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (22,'VERA CRUZ');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (23,'MARINGÁ');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (24,'LONDRINA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (25,'CURITIBA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (26,'PONTA GROSSA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (27,'CAFELÂNDIA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (28,'MISSAL');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (29,'CIANORTE');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (30,'CORNÉLIO PROCÓPIO');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (31,'QUATRO PONTES');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (32,'OURO VERDE DO OESTE');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (33,'DIAMANTE DO OESTE');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (34,'CATANDUVAS');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (35,'TERRA ROXA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (36,'PATO BRANCO');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (37,'FRANCISCO BELTRÃO');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (38,'PALMAS');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (39,'CAPANEMA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (40,'RECIFE');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (41,'FLORIANÓPOLIS');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (42,'PORTO ALEGRE');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (43,'SÃO PAULO');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (44,'RIO DE JANEIRO');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (45,'ITAJAÍ');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (46,'JOINVILE');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (47,'OLINDA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (48,'SALVADOR');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (49,'JOÃO PESSOA');

INSERT INTO TB_CIDADE (CID_CODIGO,CID_DESCRICAO)
   VALUES (50,'VITÓRIA');


INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (1,'RUA PARANÁ');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (2,'RUA ARGENTINA');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (3,'RUA ALAGOAS');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (4,'AVENIDA BRASIL');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (5,'RUA RIO DE JANEIRO');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (6,'AVENIDA JOÃO XXIII');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (7,'AVENIDA PEDRO SOCCOL');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (8,'AVENIDA JOSÉ CALEGARI');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (9,'RUA MINAS GERAIS');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (10,'RUA RIO GRANDE DO NORTE');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (11,'AVENIDA LAGOA VERMELHA');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (12,'AVENIDA SOLEDADE');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (13,'RUA PARAGUAI');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (14,'RUA SANTA CATARINA');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (15,'RUA ACRE');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (16,'RUA BAHIA');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (17,'RUA PERNAMBUCO');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (18,'RUA AMAPÁ');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (19,'RUA CEREJEIRA');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (20,'RUA KAROL WOITYLA');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (21,'RUA MATO GROSSO');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (22,'RUA PIAUÍ');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (23,'AVENIDA REPÚBLICA ARGENTINA');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (24,'AVENIDA DAS CATARATAS');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (25,'AVENIDA JUSCELINO KUBITSCHECK');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (26,'AVENIDA JORGE SCHIMMELPFENG');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (27,'AVENIDA BEBERIBE');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (28,'RUA PRESIDENTE KENNEDY');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (29,'RUA CASTRO ALVES');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (30,'RUA CARLOS GOMES');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (31,'RUA CURITIBA');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (32,'RUA OLAVO BILAC');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (33,'RUA RIO GRANDE DO SUL');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (34,'RUA RECIFE');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (35,'RUA 7 DE SETEMBRO');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (36,'AVENIDA TANCREDO NEVES');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (37,'RUA LONDRINA');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (38,'RUA GENERAL OZÓRIO');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (39,'RUA MANAUS');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (40,'RUA GETÚLIO VARGAS');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (41,'RUA VITÓRIA');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (42,'AVENIDA PADRE CALEGARO');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (43,'AVENIDA DOM GERALDO SIGAUD');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (44,'RUA GOIÁS');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (45,'AVENIDA CASTELO BRANCO');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (46,'AVENIDA BOA VIAGEM');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (47,'AVENIDA SANTOS DUMONT');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (48,'RUA SALGADO FILHO');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (49,'RUA SÃO SEBASTIÃO');

INSERT INTO TB_ENDERECO (END_CODIGO,END_DESCRICAO)
   VALUES (50,'RUA DO PRÍNCIPE');

INSERT INTO TB_CARGO(CAR_CODIGO, CAR_DESCRICAO, CAR_SALARIOBASE) 
VALUES(1, 'BIBLIOTECARIO', 1000);

INSERT INTO TB_CARGO(CAR_CODIGO, CAR_DESCRICAO, CAR_SALARIOBASE) 
VALUES(2, 'AUXILIAR BIBLIOTECARIO', 800);

INSERT INTO TB_CARGO(CAR_CODIGO, CAR_DESCRICAO, CAR_SALARIOBASE) 
VALUES(3, 'ZELADOR', 750);

INSERT INTO TB_CARGO(CAR_CODIGO, CAR_DESCRICAO, CAR_SALARIOBASE) 
VALUES(4, 'ASSISTENTE BIBLIOTECARIO', 800);

INSERT INTO TB_CARGO(CAR_CODIGO, CAR_DESCRICAO, CAR_SALARIOBASE) 
VALUES(5, 'ESTAGIARIO', 300);


INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(1, 'ANA PAULA DA SILVA', '99098784', '098.675.777-89', 1, 2, 3, 1);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(2, 'ANA ROSA DE APARECIDA', '77994523', '154.897.345-93', 2, 1, 1, 2);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(3, 'BRUNA OLIVEIRA', '78654367', '543.986.431-12', 5, 3, 2, 1);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(4, 'BRUNO RAFAEL SOUZA', '87654345', '087.876.953-54', 4, 1, 2, 2);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(5, 'CARLA DE CAMARGO', '98769876', '873.897.435-93', 3, 4, 6, 3);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(6, 'CARLOS PEREIRA', '34651267', '123.321.431-12', 2, 10, 12, 15);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(7, 'CRISTIANE DA SILVA', '87654833', '074.675.555-89', 2, 9, 8, 11);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(8, 'CRISTIANO FAGUNDES', '99882223', '222.121.345-93', 3, 14, 10, 13);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(9, 'DAIANE APARECIDA', '90874367', '123.987.111-12', 1, 16, 17, 12);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(10, 'DEBORAH DE LIMA', '99652145', '564.321.953-54', 1, 20, 21, 30);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(11, 'DIEGO MACHADO', '34459876', '999.234.435-43', 1, 31, 29, 45);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(12, 'DOUGLAS PEREIRA', '56651547', '099.123.456-12', 2, 40, 49, 31);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(13, 'JOHNY BITENCOURT', '77098777', '909.808.777-12', 5, 32, 23, 41);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(14, 'JULIANA GONÇALVES', '99886677', '111.222.345-93', 4, 21, 41, 22);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(15, 'JULIANO VASCONCELOS', '12344367', '333.111.431-12', 1, 33, 32, 31);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(16, 'JOAQUIM PEREIRA', '11123445', '123.123.123-54', 2, 41, 42, 42);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(17, 'ELAINE MALLMAN', '98799996', '666.897.435-93', 3, 44, 46, 43);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(18, 'EDUARDO GOMES', '88881267', '777.321.555-12', 2, 11, 22, 45);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(19, 'EMANUEL DIAS PEREIRA', '22254222', '222.622.555-89', 2, 19, 18, 42);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(20, 'FABIANA NOBREGA', '11121123', '999.111.345-93', 3, 34, 30, 33);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(21, 'FERNANDO TEIXEIRA', '44444367', '444.987.111-12', 5, 46, 47, 42);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(22, 'GABRIELA FAGUNDES', '33353335', '345.111.666-54', 4, 47, 42, 41);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(23, 'GABRIEL MACHADO', '31119876', '911.211.435-43', 1, 21, 39, 35);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE) 
VALUES(24, 'GUSTAVO PEREIRA', '56111547', '011.111.411-12', 2, 28, 39, 28);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(25, 'HEITOR DAMACENO', '55522211', '321.654.987-12', 1, 26, 23, 29);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(26, 'IVO MACHADO', '22525501', '789.254.987-02', 2, 32, 37, 35);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(27, 'KARLA RODRIGUES', '25836914', '258.159.987-99', 5, 41, 45, 49);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(28, 'LAUANA DE SOUZA', '14715425', '333.232.121-02', 4, 17, 28, 49);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(29, 'LAURA PEREIRA', '96395175', '157.555.157-57', 1, 28, 39, 42);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(30, 'LAURINDO BITENCOURT', '99955586', '111.114.411-25', 2, 16, 18, 47);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(31, 'LUCIANO RODRIGUES', '69696958', '474.575.788-77', 3, 12, 43, 10);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(32, 'LINDAUVA DE LIMA', '12115425', '124.123.121-09', 2, 21, 32, 43);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(33, 'MAIARA DAMACENO', '98987845', '101.205.604-11', 1, 9, 14, 33);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(34, 'MARIA MACHADO', '29995588', '157.367.987-14', 2, 12, 47, 25);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(35, 'MARIO RODRIGUES', '87822214', '242.242.987-11', 4, 12, 24, 36);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(36, 'MARIANA DE SOUZA', '12457856', '213.224.129-02', 5, 30, 20, 40);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(37, 'NAIARA PEREIRA', '25236475', '147.124.985-07', 1, 19, 37, 45);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(38, 'NICOLE BITENCOURT', '14257846', '414.457.421-27', 2, 49, 38, 27);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(39, 'NICOLAS RODRIGUES', '52526958', '147.741.001-75', 3, 22, 23, 20);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(40, 'ORLANDO DE LIMA', '99115525', '101.888.987-25', 2, 41, 22, 13);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(41, 'OTAVIO RODRIGUES', '22246958', '224.442.788-49', 3, 26, 37, 48);
INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(42, 'ODAIR DE LIMA', '95198795', '999.487.129-09', 2, 50, 20, 30);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(43, 'OSMARINO DAMACENO', '87789845', '201.105.904-91', 1, 15, 24, 39);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(44, 'PAULO MACHADO', '99778858', '805.388.988-15', 2, 19, 20, 38);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(45, 'PAULA RODRIGUES', '99772424', '542.542.547-18', 3, 24, 34, 39);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(46, 'PATRICIA DE SOUZA', '456784599', '809.299.177-07', 2, 30, 40, 20);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(47, 'PEDRO PEREIRA', '67589147', '058.474.574-88', 1, 49, 27, 35);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(48, 'ROSA BITENCOURT', '66448877', '114.117.412-22', 4, 28, 18, 9);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(49, 'SAMUEL RODRIGUES', '87459864', '022.221.229-25', 3, 12, 13, 10);

INSERT INTO TB_FUNCIONARIO(FUN_CODIGO, FUN_NOME, FUN_RG, FUN_CPF, FUN_CODCARGO, FUN_CODENDERECO, FUN_CODBAIRRO, FUN_CODCIDADE)
VALUES(50, 'TATIANE FERREIRA', '55477845', '052.565.987-87', 5, 41, 28, 33);


INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(1, 'ABRIL', 1, 1, 1, '11-0000-0001', 'ANDRE');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(2, 'PANINI', 2, 2, 2, '11-0000-0002', 'PEDRO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(3, 'MYTHOS', 3, 3, 3, '11-0000-0003', 'MARCOS');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(4, 'ATICA', 4, 4, 4, '11-0000-0004', 'ARTUR');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(5, 'ESCALA', 5, 5, 5, '11-0000-0005', 'EVERTON');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(6, 'VISUAL BOOKS', 6, 6, 6, '11-0000-0006', 'VITOR');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(7, 'SCIPIONE', 7, 7, 7, '11-0000-0007', 'SANDRA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(8, 'UFPR', 8, 8, 8, '41-0000-0008', 'ITAMAR');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(9, 'UFRJ', 9, 9, 9, '21-0000-0008', 'DJONI');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(10, 'POSITIVO', 10, 10, 10, '41-0000-0010', 'JULIANO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(11, 'BRAINSTORE', 11, 11, 11, '11-0000-0011', 'LUCIANO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(12, 'OPERA GRAPHICA', 12, 12, 12, '11-0000-0012', 'JORGE');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(13, 'DEVIR', 13, 13, 13, '11-0000-0013', 'TIAGO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(14, 'PANDORA BOOKS', 14, 14, 14, '11-0000-0014', 'ALEXANDRE');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(15, 'HEROIS.COM', 15, 15, 15, '11-0000-0015', 'JOAO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(16, 'UNIVERSO HQ', 16, 16, 16, '11-0000-0016', 'HUMBERTO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(17, 'ARGOS', 17, 17, 17, '11-0000-0017', 'HUGO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(18, 'ARTE E CIENCIA', 18, 18, 18, '11-0000-0018', 'CLAUDIO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(19, 'AYMARA', 19, 19, 19, '11-0000-0019', 'MICHELE');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(20, 'BASE', 20, 20, 20, '11-0000-0020', 'FABIO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(21, 'DCL', 21, 21, 21, '11-0000-0021', 'MARCELO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(22, 'DIMENSAO', 22, 22, 22, '11-0000-0022', 'FABIAN');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(23, 'DISAL', 23, 23, 23, '11-0000-0023', 'GUILHERME');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(24, 'SM', 24, 24, 24, '11-0000-0024', 'RONALDO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(25, 'EDIFURB', 25, 25, 25, '47-0000-0025', 'MICHEL');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(26, 'EDIOURO', 26, 26, 26, '11-0000-0026', 'JEFERSON');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(27, 'EDIPUCRS', 27, 27, 27, '51-0000-0027', 'ANA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(28, 'EDITORA DO BRASIL', 28, 28, 28, '11-0000-0028', 'PAULA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(29, 'EDUEL', 29, 29, 29, '11-0000-0029', 'AIRTON');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(30, 'EDUEM', 30, 30, 30, '11-0000-0030', 'ROMUALDO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(31, 'EDUFRGS', 31, 31, 31, '51-0000-0031', 'NELSON');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(32, 'FTD', 32, 32, 32, '11-0000-0032', 'RAFAEL');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(33, 'EDUEM', 33, 33, 33, '11-0000-0033', 'FELIPE');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(34, 'GLOBAL', 34, 34, 34, '11-0000-0034', 'FERNANDO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(35, 'GROUND', 35, 35, 35, '11-0000-0035', 'EMANUEL');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(36, 'GUANABARA KOOGAN', 36, 36, 36, '11-0000-0036', 'OSCAR');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(37, 'HARBRA', 37, 37, 37, '11-0000-0037', 'NELCIMAR');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(38, 'KOMEDI', 38, 38, 38, '11-0000-0038', 'VALDEMAR');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(39, 'LAROUSSE DO BRASIL', 39, 39, 39, '11-0000-0039', 'RITA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(40, 'MACKENZIE', 40, 40, 40, '11-0000-0040', 'AMELIA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(41, 'MACMILLAN', 41, 41, 41, '11-0000-0041', 'IRMA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(42, 'MARTINS FONTES', 42, 42, 42, '11-0000-0042', 'IDA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(43, 'MELHORAMENTOS', 43, 43, 43, '11-0000-0043', 'LEOPOLDO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(44, 'MR BENS', 44, 44, 44, '11-0000-0044', 'ANDERSON');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(45, 'MULTI MARCAS EDITORIAIS', 45, 45, 45, '11-0000-0045', 'RUDIMAR');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(46, 'NOVA FRONTEIRA', 46, 46, 46, '11-0000-0046', 'DESIREE');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(47, 'NOVA GERACAO', 47, 47, 47, '11-0000-0047', 'ICARO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(48, 'ODYSSEUS', 48, 48, 48, '11-0000-0048', 'SAMUEL');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(49, 'PIONEIRA', 49, 49, 49, '11-0000-0049', 'FABRICIO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(50, 'SARAIVA', 50, 50, 50, '11-0000-0050', 'GUSTAVO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(51, 'GLOBO MARCAS', 1, 2, 3, '11-0000-0051', 'FAUSTO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(52, 'UAPE', 2, 3, 4, '11-0000-0052', 'MARCIO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(53, 'MODERNA', 3, 4, 1, '11-0000-0053', 'ANGELA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(54, 'PRENTICE-HALL',13,14,11, '11-0000-0054', 'PAULA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(55, 'ATLAS', 23,24,21, '11-0000-0055', 'PAULO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(56, 'CAMPUS', 33, 34, 31, '11-0000-0056', 'JOSÉ');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(57, 'AMACOM', 43, 44, 41, '11-0000-0057', 'PEDRO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(58, 'ESFERA', 35, 45, 15, '11-0000-0058', 'CARLOS');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(59, 'LTC', 36, 46, 16, '11-0000-0059', 'EUDARDO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(60, 'LISA LIVROS IRRADIANTES', 37, 47, 17, '11-0000-0060', 'MARIA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(61, 'ENSINO RENOVADO', 38, 48, 18, '11-0000-0061', 'CARLA');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(62, 'DIFEL', 39, 49, 19, '11-0000-0062', 'CARLOS');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(63, 'LISBOA', 32, 42, 12, '11-0000-0063', 'ANTONIO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(64, 'BRASILIENSE', 33, 43, 13, '11-0000-0064', 'PEDRO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(65, 'RECORD', 35, 45, 15, '11-0000-0065', 'PAULO');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(66, 'INFOBOOK', 32, 42, 12, '11-0000-0066', 'JOAQUIM');

INSERT INTO TB_EDITORA (EDI_CODIGO, EDI_NOME, EDI_CODENDERECO, EDI_CODCIDADE, EDI_CODBAIRRO, EDI_FONE, EDI_CONTATO)
VALUES(67, 'E. BLUCHER', 31, 41, 11, '11-0000-0067', 'CLODOALDO');


INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (1, 'VANESA DAMACENO BARBOSA', '52791962', 17, '267', 33, 28, '41-3357-9838', 7, '286.209.389-84');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (2, 'JOAQUIM FRANCISCO SOUZA', '26978413', 34, '3729', 25, 13, '97-3415-8156', 7, '934.821.016-30');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (3, 'DURINAM SALQUEIRO', '39426923', 36, '274', 45, 31, '44-2235-7842', 14);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (4, 'FELIPE SANTOS', '82640645', 45, '836', 24, 39, '32-4675-5421', 21, '784.527.894-52');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (5, 'EMANUAL AUGUSTO TAVARES', '93492349', 43, '7217', 5, 39, '12-7934-5278', 7, '278.964.537-84');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (6, 'ADAMASTOR JATOBA MELLO', '964238138', 12, '36', 35, 39, '44-5796-3428', 14);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (7, 'JERTRUDES SILVA SOUZA ', '964983321', 41, '7864', 7, 39, '45-5793-4516', 14, '278.554.936-45');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (8, 'SUZI RAMOS NETO', '239734652', 29, '456', 17, 39, '73-1955-7438', 21, '789.538.754-21');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (9, 'TEOBALDO PISQUILA', '783165977', 21, '8942', 9, 6, '49-6378-1444', 7);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (10, 'VANDIER MACIEL DE SOUZA', '25834831', 1, '419', 41, 50, '11-2245-7967', 7);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (11, 'ISMAEL GARCIA', '3768121', 45, '1159', 15, 49, '45-3578-6969', 7);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (12, 'RODRIGO PERREIRA', '9648236', 32, '731', 17, 39, '54-3795-4216', 21, '432.256.789-45');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (13, 'JAIR BASTOS FERREIRA', '39476592', 17, '171', 48, 39, '45-3347-9442', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (14, 'ANTONIO OLIVEIRA', '68925672', 9, '157', 45, 49, '44-3179-5312', 14, '553.421.789-56');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (15, 'VALENTIM REZENDE ', '34953285', 17, '453', 42, 41, '73-1522-7456', 14, '578.694.533-64');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (16, 'MATILDE ROCHA GOMES', '4921693496', 33, '6892', 17, 46, '12-4578-9631', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (17, 'VERONICA VICENTE CARDOSO', '254936592', 9, '645', 45, 39, '35-7159-2468', 14, '557.893.652-41');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (18, 'VALDIR VEDOKA SANSHES', '5531564', 21, '333', 32, 1, '14-7896-3255', 7);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (19, 'BENEDITA VICENTI COSTA', '4689219', 14, '1678', 41, 21, '12-4896-3795', 7);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (20, 'SONIA AMARAL BEZERRA', '68216924', 24, '1334', 50, 30, '22-4567-8913', 14, '457.896.312-45');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (21, 'MARCOS BORGES', '83497720', 21, '2341', 34, 39, '75-4284-3964', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (22, 'EMERSON OLIVEIRA BRANCO', '11005932', 39, '3452', 49, 25, '47-8542-4937', 7, '785.431.256-79');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (23, 'NESTOR VICTOR SANTOS', '62492200', 23, '412', 11, 39, '75-6789-4246', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (24, 'FATIMA DOMINGUES CABAL', '59634891', 35, '7456', 43, 42, '24-379-6452', 14);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (25, 'ANICLETO SCHEFER', '25498379', 20, '4573', 17, 26, '43-2167-8945', 14);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (26, 'JIHAD SARHAN', '90285876', 40, '622', 33, 31, '75-3246-1986', 21, '789.453.367-89');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (27, 'TEREZINHA SCHIZIACK', '13972395', 50, '345', 7, 45, '45-3278-9451', 14, '889.634.521-27');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (28, 'MATEUS SARAIVA', '39548538', 5, '3467', 1, 35, '43-2189-7624', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (29, 'DANIEAL VASCONCELO', '82048572', 45, '732', 47, 35, '53-2796-4528', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (30, 'PEDRO DE LARRA CARDOSO', '71037475', 21, '623', 37, 8, '44-2379-5642', 7, '899.645.278-33');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (31, 'JOSE HENRIQUE AMADO', '11887424', 7, '724', 21, 3, '78-9345-6178', 7);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (32, 'RAMUNDO FERREIRA ROCHA', '11094875', 1, '234', 7, 9, '65-4982-1112', 14, '389.645.562-14');
	
INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (33, 'ROSELAINE RODRIGUES', '18947264', 39, '621', 43, 50, '45-9632-6996', 21, '534.789.645-27');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (34, 'FREDERICO FERRARI', '78234975', 21, '67', 25, 39, '45-2435-6784', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (35, 'MIRNA MARCOLIM', '275924974', 19, '87', 43, 47, '78-5423-9645', 7);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (36, 'JUDITE FONTANA', '72932034', 15, '234', 7, 25, '42-7935-6241', 14, '778.964.523-12');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (37, 'GENOFRA PEIXOTO', '20495729', 4, '624', 4, 41, '95-4421-7351', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (38, 'IRACEMA NUNES DA SILZA SAURO', '452108572', 29, '72', 17, 39, '96-5324-9788', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (39, 'AGENOR PERREIRA SILVA', '28733465', 37, '99', 11, 30, '55-3487-7521', 7, '224.578.963-42');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (40, 'SALDI ROVANI', '18742623', 50, '484', 9, 20, '75-424-1834', 21, '224.578.956-42');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (41, 'PAMELA SARDINHA NUNES', '190875342', 39, '2642', 19, 50, '12-3345-7316', 7);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (42, 'THERESA PAES', '99174234', 38, '555', 50, 39, '48-3537-4219', 14, '224.578.963-45');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (43, 'ADALBERTO LORENCINI', '1234872', 29, '2456', 45, 39, '45-3279-3561', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (44, 'NALIGIA LOMBALDO', '1283164', 36, '4563', 23, 47, '45-3786-4532', 7, '553.378.964-52');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (45, 'SAYONARA SANTOS JUNIOR', '18731264', 29, '34512', 17, 39, '22-3345-6789', 14, '554.478.875-21');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (46, 'NATANAEL MENDES', '1237643', 8, '5341', 5, 20, '54-3217-8964', 21);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (47, 'SINVAL TONOLO TONTINI', '12381243', 6, '7223', 42, 39, '53-3412-4679', 14, '774.639.784-21');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL, CLI_CPF)
VALUES (48, 'ALFANIO CORTES ROCHA', '123213356', 13, '3445', 14, 39, '78-3631-2459', 7, '445.378.639-78');

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (49, 'JOSIMEIRE CALGARO JUVENAL', '23495436', 44, '341', 2, 47, '78-3542-8963', 7);

INSERT INTO TB_CLIENTE(CLI_CODIGO, CLI_NOME, CLI_RG, CLI_CODENDERECO, CLI_NUMERO, CLI_CODBAIRRO, CLI_CODCIDADE, CLI_FONE, CLI_PRAZODEVOL)
VALUES (50, 'FELISBIRNA MENEZES PORTILLO', '91237534', 50, '627', 50, 37, '45-3278-9341', 21);


INSERT INTO TB_CATEGORIA(CAT_CODIGO, CAT_DESCRICAO)
VALUES( 1, 'INFORMÁTICA');

INSERT INTO TB_CATEGORIA(CAT_CODIGO, CAT_DESCRICAO)
VALUES( 2, 'MATEMATICA');

INSERT INTO TB_CATEGORIA(CAT_CODIGO, CAT_DESCRICAO)
VALUES( 3, 'LINGUA PORTUGUESA');

INSERT INTO TB_CATEGORIA(CAT_CODIGO, CAT_DESCRICAO)
VALUES( 4, 'GEOGRAFIA');

INSERT INTO TB_CATEGORIA(CAT_CODIGO, CAT_DESCRICAO)
VALUES( 5, 'HISTÓRIA');

INSERT INTO TB_CATEGORIA(CAT_CODIGO, CAT_DESCRICAO)
VALUES( 6, 'BANCO DE DADOS');


INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(1, 'COMPUTAÇÃO BÁSICA E PROGRAMAÇÃO', 50, 1, 1, '1977', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(2, 'O COMPUTADOR COMO FERRAMENTA NA EDUCAÇÃO DE JOVENS E ADULTOS', 7  , 1, 1, '2006', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(3, 'COMPUTADORES, ESCOLA E SOCIEDADE', 7, 1, 3, '1988', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(4, 'COMPUTATION: FINITE AND INFINITE MACHINES', 49, 1, 2, '1967', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(5, 'ANÁLISE DE SISTEMAS: TEORIA E PRÁTICA', 50, 1, 11, '1973', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(6, 'ANÁLISE DE SISTEMAS PARA SISTEMAS DE INFORMAÇÃO POR COMPUTADOR', 38, 1, 3, '1987', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(7, 'COMPUTER DATA PROCESSING AND RPG PROGRAMMING', 49, 1, 1, '1970', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(8, 'COMPUTER GLOSSARY: THE COMPLETE ILLUSTRATED DESK REFERENCE', 36,  1, 5, '1991', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(9, 'COMPUTADOR NA EDCAÇÃO: GUIA PARA O ENSINO COM AS NOVAS TECNOLOGIAS', 28,  1, 1, '2001', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(10, 'COMPUTAÇÃO BÁSICA E PROGRAM. : CONCEITOS BÁSICOS E TÉCNICAS ELEMENT. DE PROGRAMAÇÃO, LING. SIMBÓLICA FORTRAN, FORMAS USUAIS PARA REGISTRO DE INFORM.', 50, 1, 2, '1983', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(11, 'COMPUTAÇÃO BÁSICA E PROGRAM. : CONCEITOS BÁSICOS E TÉCNICAS ELEMENTARES DE PROGRAM. , LING. SIMBÓLICA FORTRAN, FORMAS USUAIS PARA REGISTRO DE INFORM.', 53, 1, 1, '1977', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(12, 'ADVANCED ENGINEERING MATHEMATICS', 7, 2, 7, '1993', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(13, 'ADVANCED ENGINEERING MATHEMATICS', 19, 2, 8, '1999', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(14, 'ADMINIST. FINANCEIRA E ORÇAMENTÁRIA : MATEMÁT. FINANC. APLICADA, ESTRAT. FINANC., ORÇAMENTO EMPRESARIAL', 39, 2, 6, '2007', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(15, 'ÁLGEBRA LINEAR', 16, 2, 1, '1972', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(16, 'ACENTUAÇÃO GRÁFICA EM VIGOR : UMA SISTEMATIZAÇÃO CRÍTICA', 4, 3, 1, '1989', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(17, 'GEOGRAFIA DO DESENVOLVIMENTO NO BRASIL: PROBLEMAS BRASILEIROS', 52, 3, 2, '1973', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(18, 'ALFBETIZAÇÃO: A ESCRITA ESPONTÂNEA', 4, 3, 2, '1994', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(19, 'ANÁLISE, LINGUAGEM E PENSAMENTO: A DIVERSIDADE DE TEXTOS NUMA PROPOSTA SOCIOCONSTRUTIVISTA', 32, 3, 1, '2000', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(20, 'ANÁLISE SINTÁTICA TEORIA GERAL E DESCRIÇÃO DO PORTUGUÊS', 4, 3, 2, '1989', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(21, 'GEOGRAFIA DO DESENVOLVIMENTO NO BRASIL : PROBLEMAS BRASILEIROS', 23, 4, 2, '1973', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(22, 'GEOGRAFIA DO DESENVOLVIMENTO NO BRASIL : PROBLEMAS BRASILEIROS', 23, 4, 4, '1974', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(23, 'GEOGRAFIA DO DESENVOLVIMENTO NO BRASIL : PROBLEMAS BRASILEIROS', 51, 4, 5, '1978', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(24, 'GEOGRAFIA DO PARANÁ: COM FUNDAMENTOS DE GEOGRAFIA GERAL', 40, 4, 4, '1983', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(25, 'GEOGRAFIA DO PARANÁ: COM FUNDAMENTOS DE GEOGRAFIA GERAL', 43, 4, 5, '1985', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(26, 'GEOGRAFIA DO PARANÁ', 2, 4, 3, '1978', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(27, 'GEOGRAFIA DO SUBDESENVOLVIMENTO', 6, 4, 3, '1971', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(28, 'GEOGRAFIA DO SUBDESENVOLVIMENTO', 46, 4, 5, '1978', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(29, 'GEOGRAFIA DO SUBDESENVOLVIMENTO', 6, 4, 6, '1982', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(30, 'GEOGRAFIA DO SUBDESENVOLVIMENTO', 2, 4, 8, '1990', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(31, 'GEOGRAFIA DOS CONTINENTES: AMÉRICA', 7, 4, 1, '1997', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(32, 'GEOGRAFIA DOS CONTINENTES: ASIA', 7, 4, 1, '1997', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(33, 'GEOGRAFIA DOS CONTINENTES: OCIDENTAL', 7, 4, 1, '1997', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(34, 'GEOGRAFIA DOS CONTINENTES: EUROPEU', 7, 4, 1, '1997', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(35, 'A CIDADE ANTIGA : ESTUDOS SOBRE O CULTO, O DIREITO, AS INSTITUIÇÕES DA GRÉCIA E DE ROMA', 3, 5, 8, '1976', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(36, 'A CIDADE ANTIGA : ESTUDOS SOBRE O CULTO, O DIREITO, AS INSTITUIÇÕES DA GRÉCIA E DE ROMA', 3, 5, 9, '1978', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(37, 'A CIDADE ANTIGA : ESTUDOS SOBRE O CULTO, O DIREITO, AS INSTITUIÇÕES DA GRÉCIA E DE ROMA', 3, 5, 10, '1980', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(38, 'A CRISE DO ESCRAVISMO E A GRANDE IMIGRAÇÃO', 4, 5, 1, '1976', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(39, 'A CRISE DO ESCRAVISMO E A GRANDE IMIGRAÇÃO', 4, 5, 2, '1981', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(40, 'A AMAZONIA E COBIÇA INTERNACIONAL', 5, 5, 1, '1965', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(41, 'A AMAZONIA E COBIÇA INTERNACIONAL', 21, 5, 2, '1967', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(42, 'A AMAZONIA E COBIÇA INTERNACIONAL', 27, 5, 3, '1968', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(43, 'BANCO DE DADOS ORIENTADO A OBJETOS', 6, 6, 1, '1994', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(44, 'BANCOS DE DADOS: CONCEITOS, MODELOS, GERENCIADORES, PROJETO LÓGICO, PROJETO FÍSICO', 7, 6, 1, '1986', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(45, 'BANCOS DE DADOS: CONCEITOS, MODELOS, GERENCIADORES, PROJETO LÓGICO, PROJETO FÍSICO', 7, 6, 2, '1987', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(46, 'BANCOS DE DADOS: CONCEITOS, MODELOS, GERENCIADORES, PROJETO LÓGICO, PROJETO FÍSICO', 7, 6, 3, '1989', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(47, 'BANCO DE DADOS ORIENTADO A OBJETOS', 52, 6, 1, '1999', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(48, 'BANCO DE DADOS ORIENTADO A OBJETOS', 7, 6, 2, '2001', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(49, 'BANCO DE DADOS ORIENTADO A OBJETOS', 12, 6, 3, '2003', 7);

INSERT INTO TB_LIVRO(LIV_CODIGO, LIV_TITULO, LIV_CODEDITORA, LIV_CODCATEGORIA, LIV_EDICAO, LIV_ANO, LIV_PRAZOMINIMO)
VALUES(50, 'BANCOS DE DADOS: CONCEITOS, MODELOS, GERENCIADORES, PROJETO LÓGICO, PROJETO FÍSICO', 34, 6, 4, '1992', 7);



INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(1, 'ANTONIO NICOLAU YOUSSEF');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(2, 'VICENTE PAZ FERNANDEZ');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(3, 'RUI JOSÉ DE ARRUDA CAMPOS');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(4, 'JOSÉ CORDEIRO');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(5, 'JORGE PEDRO DALLEDONNE DE BARROS');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(6, 'UBIRATAN D AMBROSIO');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(7, 'MARVIN LEE MINSKY');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(8, 'ANTONY CHANDOR');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(9, 'JOHN GRAHAM');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(10, 'ROBIN WILLIAMSON');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(11, 'JAMES C. WETHERBE');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(12, 'THOMAS R GILDERSLLEVE');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(13, 'ALAN FREEDMAN');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(14, 'MARCO GASPERETTI');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(15, 'ERWIN KREYSZIG');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(16, 'MASAKAZU HOJI');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(17, 'DAVID C. MURDOCH');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(18, 'AMINI BOAINAIN HAUY');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(19, 'CARLOS CESAR GUTERRES TAVEIRA');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(20, 'ADEMAR DA SILVA');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(21, 'MARIA FERNANDES CÓCCO');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(22, 'MARCO ANTONIO HAILER');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(23, 'MIRIAM LEMLE');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(24, 'IAROSLAW WONS');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(25, 'YVES LACOSTE');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(26, 'HELIO CARLOS GARCIA');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(27, 'TITO MARCIO GARAVELLO');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(28, 'FUSTEL DE COULANGES');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(29, 'PAULA BEIGUELMAN');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(30, 'ARTHUR CEZAR FERREIRA REIS');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(31, 'SETRAG KHOSHAFIAN');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(32, 'VALDEMAR WAINGORT SETZER');

INSERT INTO TB_AUTOR(AUT_CODIGO, AUT_NOME)
VALUES(33, 'EUGÊNIO A. NASSU');


INSERT INTO TB_AUTORLIVRO(AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(3, 1, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(4, 2, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(5, 3, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(6, 3, 'NÃO');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(7, 4, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(8, 5, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(11, 6, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(12, 7, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(13, 8, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(14, 9, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(3, 10, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(3, 11, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(15, 12, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(15, 13, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(16, 14, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(17, 15, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(18, 16, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(19, 17, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(20, 18, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(21, 19, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(22, 19, 'NÃO');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(23, 20, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(19, 21, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(19, 22, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(19, 23, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(24, 24, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(24, 25, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(24, 26, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(25, 27, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(25, 28, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(25, 29, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(25, 30, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(26, 31, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(27, 31, 'NÃO');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(26, 32, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(27, 32, 'NÃO');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(26, 33, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(27, 33, 'NÃO');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(26, 34, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(27, 34, 'NÃO');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(28, 35, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(28, 36, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(28, 37, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(29, 38, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(29, 39, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(30, 40, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(30, 41, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(30, 42, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(31, 43, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(32, 44, 'SIM');

INSERT INTO TB_AUTORLIVRO(AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(32, 45, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(32, 46, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(33, 47, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(33, 48, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(33, 49, 'SIM');

INSERT INTO TB_AUTORLIVRO (AUTLIV_CODAUTOR, AUTLIV_CODLIVRO, AUTLIV_PRINCIPAL)
VALUES(32, 50, 'SIM');


INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(1, '2009-01-01', 1, 1, 1, 'ATIVA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(2, '2009-02-01', 3, 3, 3, 'ATIVA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(3, '2009-03-01', 5, 5, 5, 'CANCELADA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(4, '2009-04-01', 7, 7, 7, 'CONCLUIDA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(5, '2009-05-01', 9, 9, 9, 'ATIVA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(6, '2009-06-01', 11, 11, 11, 'CONCLUIDA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(7, '2009-07-01', 13, 13, 13, 'CANCELADA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(8, '2009-08-01', 15, 15, 15, 'ATIVA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(9, '2009-09-01', 17, 17, 17, 'CONCLUIDA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(10, '2009-10-01', 18, 19, 19, 'ATIVA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(11, '2009-11-01', 21, 21, 21, 'CANCELADA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(12, '2009-12-01', 23, 23, 23, 'CONCLUIDA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(13, '2009-01-02', 25, 25, 25, 'CONCLUIDA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(14, '2009-02-02', 27, 27, 27, 'ATIVA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(15, '2009-03-02', 29, 29, 29, 'ATIVA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(16, '2009-04-02', 31, 31, 31, 'CANCELADA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(17, '2009-05-02', 33, 33, 33, 'CANCELADA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(18, '2009-06-02', 35, 35, 35, 'CONCLUIDA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(19, '2009-01-03', 37, 37, 37, 'CONCLUIDA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(20, '2009-10-03', 39, 39, 39, 'ATIVA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(21, '2009-01-04', 41, 41, 41, 'CANCELADA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(22, '2009-05-04', 43, 43, 43, 'CONCLUIDA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(23, '2009-10-04', 45, 45, 45, 'ATIVA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(24, '2009-02-05', 47, 47, 47, 'CANCELADA');

INSERT INTO TB_RESERVA(RES_CODIGO, RES_DATA, RES_CODLIVRO, RES_CODFUNC, RES_CODCLIENTE, RES_SITUACAO)
VALUES(25, '2009-10-05', 49, 49, 49, 'CONCLUIDA');


INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (1, 12,'LOCADO');
	
INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (2, 4,'NÃO LOCADO');
INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (3, 41,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (4, 18,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (5, 10,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (6, 33,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (7, 5,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (8, 25,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (9, 46,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (10, 1,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (11, 38,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (12, 16,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (13, 22,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (14, 50,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (15, 29,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (16, 20,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (17, 42,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (18, 6,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (19, 27,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (20, 48,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (21, 21,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (22, 49,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (23, 7,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (24, 35,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (25, 14,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (26, 2,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (27, 44,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (28, 47,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (29, 26,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (30, 11,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (31, 31,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (32, 3,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (33, 23,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (34, 30,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (35, 40,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (36, 8,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (37, 17,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (38, 37,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (39, 45,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (40, 28,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (41, 24,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (42, 39,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (43, 15,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (44, 43,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (45, 13,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (46, 19,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (47, 34,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (48, 36,'NÃO LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (49, 32,'LOCADO');

INSERT INTO TB_EXEMPLAR (EXE_CODIGO,EXE_CODLIVRO, EXE_STATUS)
   VALUES (50, 9,'NÃO LOCADO');


INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (1, '2008-01-01', 5, 10);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (2, '2009-01-01', 10, 12);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (3, '2003-01-01', 12, 32);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (4, '2008-10-12',10, 50);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (5, '2003-12-07', 44, 22);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (6, '2000-07-08', 37, 22);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (7, '2005-06-08', 37, 11);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (8, '1999-11-10', 49, 1);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (9, '1998-03-12', 9, 23);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (10, '2004-12-12', 20, 30);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (11, '2001-08-09', 32, 33);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (12, '2009-01-01', 9, 12);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (13, '2007-06-03', 7, 42);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (14, '2009-10-11', 27, 31);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (15, '2009-12-02', 48, 5);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (16, '2006-06-06', 39, 44);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (17, '2002-03-02', 17, 28);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (18, '2002-12-08', 28, 37);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (19, '2002-08-07', 47, 36);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (20, '2009-01-01', 12, 29);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (21, '2003-09-10', 16, 15);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (22, '2003-01-01', 14, 38);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (23, '2001-01-01', 48, 29);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (24, '1999-01-01', 10, 30);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (25, '2008-12-06', 44, 31);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (26, '2003-03-07', 8, 46);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (27, '2007-01-07', 32, 19);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (28, '2002-07-06', 25, 38);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (29, '2008-06-09', 11, 21);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (30, '2001-07-01', 50, 50);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (31, '2005-11-05', 38, 32);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (32, '2002-12-05', 3, 7);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (33, '2008-12-06', 21, 41);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (34, '2001-10-7', 39, 42);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (35, '2002-09-08', 37, 43);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (36, '2000-08-09', 36, 44);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (37, '2000-07-10', 35, 45);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (38, '2007-06-11', 34, 46);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (39, '2000-05-12', 33, 47);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (40, '1997-04-01', 30, 48);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (41, '2006-03-02', 29, 49);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (42, '2001-02-03', 27, 50);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (43, '2002-01-04', 37, 43);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (44, '1999-12-5', 38, 21);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (45, '2003-05-04', 2, 1);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (46, '2008-10-09', 7, 46);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (47, '2006-08-07', 35, 43);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (48, '2006-08-07', 15, 34);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (49, '2004-06-05', 3, 42);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (50, '2003-01-02', 4, 5);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (51, '2005-03-04', 6, 7);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (52, '2006-04-05', 7, 8);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (53, '2009-07-08', 30, 2);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (54, '2009-07-08', 15, 4);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (55, '2005-01-03', 7, 9);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (56, '2006-02-04', 8, 10);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (57, '2005-05-10', 20, 25);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (58, '2008-06-12', 24, 30);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (59, '2002-04-08', 16, 20);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (60, '2001-07-04', 28, 35);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (61, '2004-08-06', 32, 40);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (62, '2004-09-10', 32, 43);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (63, '2007-09-08', 35, 44);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (64, '2003-10-02', 40, 50);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (65, '2003-02-03', 3, 4);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (66, '2006-06-06', 6, 6);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (67, '2002-08-13', 21, 34);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (68, '2000-12-11', 33, 22);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (69, '1998-10-10', 22, 21);

INSERT INTO TB_EMPRESTIMO (EMP_CODIGO, EMP_DATA, EMP_CODCLIENTE, EMP_CODFUNCIONARIO) VALUES (70, '1997-06-08', 23, 27);


INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (2, 16, '2007-10-16', '2007-10-23', '2007-10-27', 25, 2);
	
INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (38, 24, '1999-02-01', '1999-02-07', '1999-02-11', 11, 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (20, 50, '2008-08-21', '2008-08-27', '2008-08-31', 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (27, 3, '2009-06-21', '2009-06-28', '2009-07-01', 3, 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (42, 38, '2006-07-22', '2006-07-29', '2006-08-02', 4, 3);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (23, 11, '1999-11-03', '1999-11-18', '1999-11-22', 5);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (48, 27, '2007-10-15', '2007-10-22', '2007-10-26', 3);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (13, 6, '2009-03-29', '2009-04-05', '2009-04-09', 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (33, 1, '2005-01-01', '2005-01-08', '2005-01-11', 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (17, 19, '2009-01-11', '2009-01-18', '2009-01-22', 13, 10);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (6, 36, '2007-10-16', '2007-10-23', '2007-10-27', 12, 11);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (44, 31, '2009-09-10', '2009-09-17', '2009-09-21', 22, 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (46, 43, '1999-02-13', '1999-02-20', '1999-02-24', 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (36, 9, '2008-04-27', '2008-05-04', '2008-05-08', 1, 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (25, 46, '2009-09-09', '2009-09-16', '2009-09-20', 3, 5);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (11, 41, '2008-01-07', '2008-01-14', '2008-01-18', 10);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (22, 13, '2008-10-11', '2008-10-18', '2008-10-22', 12);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (10, 40, '2007-06-05', '2007-06-12', '2007-06-16', 4, 12);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (43, 23, '2009-02-19', '2009-02-26', '2009-03-02', 17, 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (18, 47, '2008-12-02', '2008-12-09', '2008-12-13', 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (8, 33, '2008-11-18', '2008-11-25', '2008-11-29', 3, 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (3, 34, '2007-10-16', '2007-10-23', '2007-10-27', 21, 7);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (29, 25, '2008-01-07', '2008-01-14', '2008-01-18', 5, 9);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (24, 26, '2009-06-20', '2009-06-27', '2009-07-01', 10);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (1, 8, '2008-11-14', '2008-11-21', '2008-11-25', 9);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (30, 12, '2006-08-03', '2006-08-10', '2006-08-14', 23, 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (50, 44, '2005-07-20', '2005-07-27', '2005-07-31', 6, 1);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (40, 15, '2005-02-23', '2005-03-02', '2005-03-06', 9, 12);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (28, 17, '2006-01-12', '2006-01-19', '2006-01-23', 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (16, 45, '2006-07-19', '2006-07-26', '2006-07-30', 7, 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (41, 20, '2005-12-01', '2005-12-08', '2005-12-12', 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (45, 14, '1999-04-15', '1999-04-22', '1999-04-26', 1, 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (21, 21, '2008-04-01', '2008-04-08', '2008-04-12', 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (26, 2, '2006-06-21', '2006-06-28', '2006-07-02', 7, 12);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (49, 22, '2007-06-06', '2007-06-13', '2007-06-17', 15, 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (19, 29, '2002-04-28', '2002-05-05', '2002-05-09', 4);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (47, 28, '2005-01-24', '2005-01-31', '2005-02-04', 8);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (14, 49, '2003-08-03', '2003-08-10', '2003-08-14', 9);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (31, 37, '2005-12-25', '2006-01-01', '2006-01-05', 10);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (35, 48, '2003-09-12', '2003-09-19', '2003-09-23', 9, 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (37, 30, '2003-10-12', '2003-10-19', '2003-10-23', 16, 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (39, 32, '2002-05-06', '2002-05-13', '2002-05-17', 0);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (32, 5, '2002-03-31', '2002-04-07', '2002-04-11', 8);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (34, 10, '2001-07-18', '2001-07-25', '2001-07-29', 9);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (5, 39, '2001-10-08', '2001-10-15', '2001-10-19', 10);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (4, 35, '2000-05-04', '2000-05-11', '2000-05-15', 10, 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (7, 42, '1999-11-11', '1999-11-18', '1999-11-22', 2);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_CODRESERVA, EXEPRE_VALORMULTA)
   VALUES (9, 4, '2001-09-13', '2001-09-20', '2001-09-24', 6, 8);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (12, 7, '2002-06-22', '2002-06-29', '2002-07-03', 9);

INSERT INTO TB_EXEMPLAREMPRESTIMO (EXEPRE_CODEXEMPLAR, EXEPRE_CODEMPRESTIMO, EXEPRE_DTPREVDEV, EXEPRE_DTDEVMUL, EXEPRE_DTPGMUL, EXEPRE_VALORMULTA)
   VALUES (15, 18, '2000-11-14', '2000-11-21', '2000-11-25', 0);

